const sectionConfig = [
  {
    id: "section2",
    className: ["section2"],
    title: "Recommended Courses",
    seeAllBtn: "See All",
    containerId: "recommendedCoursesContainer",
    duration: true,
  },
  {
    id: "section3",
    className: ["section3"],
    title: "Recommended Books",
    seeAllBtn: "See All",
    containerId: "recommendedBooksContainer",
    duration: false,
  },
  {
    id: "section4",
    className: ["section4"],
    title: "Recommended Videos",
    seeAllBtn: "See All",
    containerId: "recommendedVideosContainer",
    duration: false,
  },
  {
    id: "section5",
    className: ["section5"],
    title: "Recommended Articles",
    seeAllBtn: "See All",
    containerId: "recommendedArticlesContainer",
    duration: false,
  },
  {
    id: "section6",
    className: ["section6"],
    title: "Recommended Podcasts",
    seeAllBtn: "See All",
    containerId: "recommendedPodcastsContainer",
    duration: false,
  },
  {
    id: "section7",
    className: ["section7"],
    title: "Recommended Graphical Summaries",
    seeAllBtn: "See All",
    containerId: "recommendedGraphicalSummariesContainer",
    duration: false,
  },
  {
    id: "explore",
    className: ["explore"],
    title: "explore",
    seeAllBtn: "See All",
    containerId: "seeAllContainer",
    duration: true,
  }
];
