const config = {
  sectionConfig: [
    {
      id: "for-you-section",
      className: ["for-you-section"],
      title: "Just for you",
      seeAllBtn: "",
      containerId: "for-you-container",
      duration: false,
    },
    {
      id: "section2",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "Recommended Courses",
      seeAllBtn: "See All",
      containerId: "recommendedCoursesContainer",
      duration: true,
    },
    {
      id: "section3",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "Recommended Books",
      seeAllBtn: "See All",
      containerId: "recommendedBooksContainer",
      duration: false,
    },
    {
      id: "section4",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "Recommended Videos",
      seeAllBtn: "See All",
      containerId: "recommendedVideosContainer",
      duration: false,
    },
    {
      id: "section5",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "Recommended Articles",
      seeAllBtn: "See All",
      containerId: "recommendedArticlesContainer",
      duration: false,
    },
    {
      id: "section6",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "Recommended Podcasts",
      seeAllBtn: "See All",
      containerId: "recommendedPodcastsContainer",
      duration: false,
    },
    {
      id: "section7",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "Recommended Graphical Summaries",
      seeAllBtn: "See All",
      containerId: "recommendedGraphicalSummariesContainer",
      duration: false,
    },
    {
      id: "explore",
      className: ["explore"],
      title: "explore",
      seeAllBtn: "See All",
      containerId: "seeAllContainer",
      duration: true,
    },
  ],
  exploreConfig: [
    {
      id: "exploreCourses",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "All Courses",
      seeAllBtn: "See All",
      containerId: "allCoursesContainer",
      duration: true,
    },
    {
      id: "exploreBooks",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "All Books",
      seeAllBtn: "See All",
      containerId: "allBooksContainer",
      duration: false,
    },
    {
      id: "exploreVideos",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "All Videos",
      seeAllBtn: "See All",
      containerId: "allVideosContainer",
      duration: false,
    },
    {
      id: "exploreArticles",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "All Articles",
      seeAllBtn: "See All",
      containerId: "allArticlesContainer",
      duration: false,
    },
    {
      id: "explorePodcasts",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "All Podcasts",
      seeAllBtn: "See All",
      containerId: "allPodcastsContainer",
      duration: false,
    },
    {
      id: "exploreGraphical",
      className: ["recommendedSections"],
      containerClassName: "recommendedContainer",
      title: "All Graphical Summaries",
      seeAllBtn: "See All",
      containerId: "allGraphicalSummariesContainer",
      duration: false,
    },
  ],
  userConfig: {
    firstName: "Michel",
    lastName: "Scoot",
    email: "michel@gmail.com",
    growthProfile:"Newcomer",
    profilePicture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWHkQVsb4b-CS96W5FbUgyBLTrtpBNE-DSHg&usqp=CAU",
    badges: [
      {
        active:false,
        achievementTitle: "achievement",
        achievementIcon:
          "https://github.githubassets.com/images/modules/profile/achievements/pull-shark-default.png",
      },
      {
        active:true,
        achievementTitle: "achievement 2",
        achievementIcon:
          "https://github.githubassets.com/images/modules/profile/achievements/yolo-default.png",
      },
    ],
    recommendedTags: ["Conflict", "Coaching"],
    isLoggedIn: true,
  },
  appTheme: {},
  filterArr: [],
  sortType: "Default",
  activeSeeAll: "",
  cardsLimit: 7,
  isSeeAllScreen: false,
  fetchingNextPage: false,
  page: 1,
  pageSize: 5,
  lastIndex: 0,
  renderedCard: 0,
  search: "",
};
