const config = {
  sectionConfig: [
    {
      id: "for-you-section",
      className: ["for-you-section"],
      title: "Just For You",
      seeAllBtn: "",
      containerId: "for-you-container",
      duration: false,
    },
    {
      id: "section2",
      className: ["section2"],
      title: "Recommended Courses",
      seeAllBtn: "See All",
      containerId: "recommendedCoursesContainer",
      duration: true,
    },
    {
      id: "section3",
      className: ["section3"],
      title: "Recommended Books",
      seeAllBtn: "See All",
      containerId: "recommendedBooksContainer",
      duration: false,
    },
    {
      id: "section4",
      className: ["section4"],
      title: "Recommended Videos",
      seeAllBtn: "See All",
      containerId: "recommendedVideosContainer",
      duration: false,
    },
    {
      id: "section5",
      className: ["section5"],
      title: "Recommended Articles",
      seeAllBtn: "See All",
      containerId: "recommendedArticlesContainer",
      duration: false,
    },
    {
      id: "section6",
      className: ["section6"],
      title: "Recommended Podcasts",
      seeAllBtn: "See All",
      containerId: "recommendedPodcastsContainer",
      duration: false,
    },
    {
      id: "section7",
      className: ["section7"],
      title: "Recommended Graphical Summaries",
      seeAllBtn: "See All",
      containerId: "recommendedGraphicalSummariesContainer",
      duration: false,
    },
    {
      id: "explore",
      className: ["explore"],
      title: "explore",
      seeAllBtn: "See All",
      containerId: "seeAllContainer",
      duration: true,
    },
  ],
  exploreConfig: [
    {
      id: "section2",
      className: ["section2"],
      title: "All Courses",
      seeAllBtn: "See All",
      containerId: "allCoursesContainer",
      duration: true,
    },
    {
      id: "section3",
      className: ["section3"],
      title: "All Books",
      seeAllBtn: "See All",
      containerId: "allBooksContainer",
      duration: false,
    },
    {
      id: "section4",
      className: ["section4"],
      title: "All Videos",
      seeAllBtn: "See All",
      containerId: "allVideosContainer",
      duration: false,
    },
    {
      id: "section5",
      className: ["section5"],
      title: "All Articles",
      seeAllBtn: "See All",
      containerId: "allArticlesContainer",
      duration: false,
    },
    {
      id: "section6",
      className: ["section6"],
      title: "All Podcasts",
      seeAllBtn: "See All",
      containerId: "allPodcastsContainer",
      duration: false,
    },
    {
      id: "section7",
      className: ["section7"],
      title: "All Graphical Summaries",
      seeAllBtn: "See All",
      containerId: "allGraphicalSummariesContainer",
      duration: false,
    },
  ],
};
